Add lesson 2
yzubr/courses pull request #1
Opened 2024-09-26 19:22 UTC by yzubr

2024-09-28 19:45 UTC, vladshcherbin requested changes
В общем и целом, очень даже хорошо - парочка правок и вообще 🔥

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/.gitignore
этот файлик не нужен, в корне проекта файлик `.gitignore` делает тоже самое для всех папочек

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +
лишняя пустая строка

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +
лишняя пустая строка

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +
лишняя пустая строка

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +<html lang="en">
язык английский, а страничка на русском

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +  <title>Document</title>
`title` лучше ставить повыше, сразу после этих `meta`

т.к. браузер и поисковики обрабатывают файлик сверху вниз, то и название страницы они хотят получить быстрее

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +  <title>Document</title>
и название страницы укажи нормальное, соотвутствующее содержимому

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +  background-color: #18191c;
для body желательно указывать font-size (обычно 16px) и line-height (обычно 1.5 или 1.6)

font-size на случай если в браузере по умолчанию плохое значение будет
line-height чтобы легче читался текст на страничке

(можно в этом задании не менять, но это хорошая практика)

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +.container {
этот класс нигде не используется - можно удалять

в исходном варианте ширина была 940px, можно в body и добавить

```css
body {
  max-width: 940px;
  margin: 0 auto;
}
```

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +  border-top-right-radius: 3px;
радиусы ничего не делают - сверху бордера нет - можно удалять

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +nav li:hover {
обычно hover вешают на интерактивные элементы, у нас здесь есть ссылки `a`

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +    <div class="wrapper">
используй списки для списка элементов - пропадут бесполезные div-ы и семантически будет более правильно для поисковиков

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +  flex-wrap: wrap;
если здесь заменишь на no-wrap чтобы не переносилось на другую строку, то 3 элемента будут на одной и будут занимать 1/3 от всей ширины - не нужно будет задавать ширину вручную ниже

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +  width: 300px;
когда поменяешь выше на nowrap, ширину можно убрать

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +  height: 420px;
если уж очень захотелось указать высоту, то делай хотя бы `min-height` - так элементы внутри не вылезут за родителя если по высоте в сумме будут больше 420

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +.card__header {
моя рекомендация вместо бэм писать нормальные классы)

он сейчас мало где используется и в командах, где его не используют, придётся отвыкать на месте

а в реакте стили индивидуальных компонентов вообще не будут пересекаться - там он тоже бесполезен

как промежуточный вариант, можешь использовать хотя бы такие названия:

```css
.card-header {}

.card-header h2 {}
```

считай тоже самое, а линтёр не ругается и какие-никакие стандарты соблюдены :)

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +  text-align: end;
чуть выше был же `text-align: right` - его и используй здесь

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +  width: 1360px;
в футере эти стили уже не нужны будут после добавления ширины в body выше

только добавить центрирование текста (в исходном варианте текст по центру)

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +    <p>2023. Разработано компанией<a href="#">«Гарцующий пони»</a></p>
пробел между компанией и ссылкой потерялся

2024-09-28 19:45 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +  border-top-right-radius: 3px;
радиусы ничего не делают - сверху бордера нет - можно удалять

2024-10-02 21:06 UTC, yzubr commented on Lesson 2/.gitignore
fixed

2024-10-02 21:06 UTC, yzubr commented on Lesson 2/src/index.html
> +
fixed

2024-10-02 21:06 UTC, yzubr commented on Lesson 2/src/index.html
> +
fixed

2024-10-02 21:06 UTC, yzubr commented on Lesson 2/src/index.html
> +
fixed

2024-10-02 21:06 UTC, yzubr commented on Lesson 2/src/index.html
> +<html lang="en">
fixed

2024-10-02 21:06 UTC, yzubr commented on Lesson 2/src/index.html
> +  <title>Document</title>
fixed

2024-10-02 21:06 UTC, yzubr commented on Lesson 2/src/index.html
> +  <title>Document</title>
fixed

2024-10-02 21:07 UTC, yzubr commented on Lesson 2/src/style.css
> +.container {
fixed

2024-10-02 21:07 UTC, yzubr commented on Lesson 2/src/style.css
> +  border-top-right-radius: 3px;
fixed

2024-10-02 21:07 UTC, yzubr commented on Lesson 2/src/style.css
> +nav li:hover {
fixed

2024-10-02 21:07 UTC, yzubr commented on Lesson 2/src/style.css
> +  flex-wrap: wrap;
fixed

2024-10-02 21:07 UTC, yzubr commented on Lesson 2/src/style.css
> +  width: 300px;
fixed

2024-10-02 21:07 UTC, yzubr commented on Lesson 2/src/style.css
> +  height: 420px;
fixed

2024-10-02 21:07 UTC, yzubr commented on Lesson 2/src/style.css
> +.card__header {
fixed

2024-10-02 21:07 UTC, yzubr commented on Lesson 2/src/style.css
> +  text-align: end;
fixed

2024-10-02 21:07 UTC, yzubr commented on Lesson 2/src/style.css
> +  width: 1360px;
fixed

2024-10-02 21:08 UTC, yzubr commented on Lesson 2/src/index.html
> +    <p>2023. Разработано компанией<a href="#">«Гарцующий пони»</a></p>
fixed

2024-10-02 21:08 UTC, yzubr commented on Lesson 2/src/style.css
> +  border-top-right-radius: 3px;
fixed

2024-10-06 17:45 UTC, vladshcherbin requested changes
Давай добьём пару правок и в продакшен

2024-10-06 17:45 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +    <header>
переборщил с отступом внутри body

2024-10-06 17:45 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +      <div class="wrapper">
используй список для списка элементов - пропадут бесполезные div-ы и семантически будет более правильно для поисковиков

2024-10-06 17:45 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +        <article class="card">
для элементов флекс-контейнера нужно задать ширину flex-basis. если проверишь в инспекторе - ширина не у всех одинаковая

2024-10-06 17:45 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +            <img src="./assets/img/image2.png" alt="worldpress-course">
```suggestion
            <img src="./assets/img/image2.png" alt="Wordpress course">
```

в `alt` можно использовать и пробелы, и заглавные - здесь названия когда картинка не загрузилась и то, что зачитает читалка (тире не нужны)

2024-10-06 17:45 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +            <p class="card__description">WordPress — топ за свои деньги. Изучите его,
```suggestion
            <p>WordPress — топ за свои деньги. Изучите его,
```

такого класса уже нет

2024-10-06 17:45 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +  display: flex;
флекс здесь избыточен, хватило бы простого `text-align: center`

2024-10-06 17:45 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +  border-bottom: 2px solid orange;
вот тут хорошее подчёркивание, к ссылочке. и hover прекрасно бы добавляется при необходимости

вот бы ещё и в шапке был бордер у ссылочек вместо элементов списка)

2024-10-06 20:36 UTC, yzubr commented on Lesson 2/src/style.css
> +  border-bottom: 2px solid orange;
Когда был лессон 2, мы ще не знали про ховер)

2024-10-06 20:40 UTC, yzubr commented on Lesson 2/src/index.html
> +        <article class="card">
![image](https://github.com/user-attachments/assets/f24dfbac-003f-44a9-a71b-6a03b1891bf2)

я следовал инструкции)

можно для тупеньких, когда ширина все-таки нужна, а когда нет. я уже окончательно перестал понимать

2024-10-06 21:16 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +  border-bottom: 2px solid orange;
поэтому я и написал "при необходимости" 😅

2024-10-06 21:19 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +        <article class="card">
`width` почти нигде не используется

во флекс через flex / flex-basis
в гридах через grid-template-columns

в этом примере у нас флекс-контейнер поэтому вместо ширины нужно указать flex-basis или сокращением через flex

2024-10-06 21:21 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +        <article class="card">
я и сам убрал твою ширину и визуально посмотрел, что 3 элемента стали в один ряд с одинаковой шириной

а потом через инспектор посмотрел, что ширина всё же разная и в любом случае нужно указать flex-basis

2024-10-07 18:44 UTC, vladshcherbin approved these changes
Оставил пару пометок - можешь пофиксить, а можешь и не фиксить. В остальном вопросов нет, молодец 👍

2024-10-07 18:44 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +      <nav>
отступы поплыли

2024-10-07 18:44 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +            <p >WordPress — топ за свои деньги. Изучите его,
```suggestion
            <p>WordPress — топ за свои деньги. Изучите его,
```

2024-10-07 18:44 UTC, vladshcherbin commented on Lesson 2/src/style.css
> +  flex-basis: calc((940px - 40px) / 3);
```suggestion
  flex: 0 0 calc((100% - 40px) / 3);
```

лучше использовать 100% т.к. если ширина поменяется, придётся и здесь менять

2024-10-07 18:44 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +          </footer >
```suggestion
          </footer>
```

2024-10-07 18:44 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +          <header class="card-header">
`article` убирать не нужно было, просто обернуть в элемент списка

2024-10-07 19:47 UTC, yzubr commented on Lesson 2/src/index.html
> +          <header class="card-header">
Тогда вообще не понимаю смысла. Был див с вложенными артиклами, стал ул с лишками, в которых артиклы, а еще в идеале это явно в `a` обернуто. становится еще больше тегов

2024-10-07 19:48 UTC, merged

2024-10-07 20:02 UTC, vladshcherbin commented on Lesson 2/src/index.html
> +          <header class="card-header">
@yzubr всё верно, всё это было бы ещё обёрнуто в `<a>`.

Это мы с тобой понимаем, что это список, хотя бы визуально. Когда к тебе заходит поисковик или кто-то с читалки, они не знают, что это список т.к. `div` это просто группирующий элемент. Вот и получается, что список есть, но для компьютера это неясно без использования семантических тегов