Lesson 15
yzubr/courses pull request #13
Opened 2024-10-20 08:46 UTC by yzubr

2024-10-20 17:43 UTC, vladshcherbin requested changes
Парочка правок, пометок и рекомендаций - в целом все задания имеют верный результат 👍

2024-10-20 17:43 UTC, vladshcherbin commented on lesson-15/src/index.js
> +    if (category !== undefined) {
```suggestion
    if (category) {
```

проверка if вернет false, если category имеет значение undefined или другие “ложные” значения (null, 0, ‘’, false) - явно сравнивать не нужно

2024-10-20 17:43 UTC, vladshcherbin commented on lesson-15/src/index.js
> +  })
```suggestion
  console.log(await getCategoryProducts(listOfCategories, 'Electronics'))

  console.log(await getCategoryProducts(listOfCategories, 'Groceries'))
```

можно заменить на `await` и сразу вывести в консоль без лишних переменных

2024-10-20 17:43 UTC, vladshcherbin commented on lesson-15/src/index.js
> +  })
```suggestion
  async function fetchProductsNamesAndPrices(categories, categoryName) {
    const category = categories.find(({ name }) => name === categoryName)

    if (category) {
      const response = await fetch(category.url)
      const { products } = await response.json()

      return Object.fromEntries(products.map(({ price, title }) => [title, price]))
    }

    return `категория ${categoryName} не найдена`
  }

  console.log(await fetchProductsNamesAndPrices(listOfCategories, 'Electronics'))
  console.log(await fetchProductsNamesAndPrices(listOfCategories, 'Groceries'))
```

чуть зарефакторил с деструктуризацией

- пофиксил ошибку в названии ф-ции
- сократил названия параметров и переменных
- добавил деструктуризацию
- обновил if
- убрал then
- добавил пустые строчки чтобы для читаемости

2024-10-20 17:43 UTC, vladshcherbin commented on lesson-15/src/index.js
> +    console.log(groupedByCategory)
в начале домашнего есть пометка

> Каждая функция возвращает результат, который затем выводится в консоль, вместо того чтобы выводить его непосредственно внутри самой функции

2024-10-20 17:43 UTC, vladshcherbin commented on lesson-15/src/index.js
> +  getAndGroupsProductByCategory()
это функция асинхронная, но ответ мы не ждём - если обернуть в console.log, то покажет промис вместо групп продуктов

2024-10-20 17:43 UTC, vladshcherbin commented on lesson-15/src/index.js
> +  getProductByCategoryAndRerurnQuantity()
```suggestion
  async function getCategoryProductsCount(category) {
    const response = await fetch(`https://dummyjson.com/products/category/${category}`)
    const { products } = await response.json()

    return products.length
  }

  async function getProductCategories() {
    const response = await fetch('https://dummyjson.com/products?limit=20&select=title,category')
    const { products } = await response.json()

    return products.reduce((acc, { category }) => (
      acc.includes(category) ? acc : [...acc, category]
    ), [])
  }

  async function getProductCategoriesProductsCount() {
    const categories = await getProductCategories()
    console.log(categories)
    const productsInSameGroupsCount = await Promise.all(categories.map((category) => (
      getCategoryProductsCount(category)
    )))
    console.log('same products categories count', productsInSameGroupsCount)

    return Object.fromEntries(
      categories.map((category, index) => [category, productsInSameGroupsCount[index]])
    )
  }

  console.log(await getProductCategoriesProductsCount())
```

зарефакторил по заметкам из предыдущих заданий

2024-10-20 17:43 UTC, vladshcherbin commented on lesson-15/src/index.js
> +  fetchListOfProductsAndReturnPricesInGroup()
```suggestion
  async function getProductsByCategory(category) {
    const response = await fetch(`https://dummyjson.com/products/category/${category}`)
    const { products } = await response.json()

    return products
  }

  async function getCategoriesProductsInformation() {
    const categories = await getProductCategories()
    const productsByCategories = await Promise.all(categories.map((category) => (
      getProductsByCategory(category)
    )))

    return Object.fromEntries(
      categories.map((category, index) => {
        const products = productsByCategories[index]
        const prices = products.map(({ price }) => price)

        return [category, {
          products: products.map(({ title }) => title),
          cheapestPrice: Math.min(...prices),
          mostExpensivePrice: Math.max(...prices),
          averagePrice: (prices.reduce((acc, price) => acc + price, 0) / products.length).toFixed(2)
        }]
      })
    )
  }

  console.log(await getCategoriesProductsInformation())
```

зарефакторил по заметкам из предыдущих заданий

2024-10-20 17:43 UTC, vladshcherbin commented on lesson-15/src/tempCodeRunnerFile.js
какой-то бесполезный код просочился)

2024-10-21 16:52 UTC, yzubr commented on lesson-15/src/index.js
> +    console.log(groupedByCategory)
В какой-то момент я напрочь забыл об этом :)

2024-10-21 16:53 UTC, yzubr commented on lesson-15/src/tempCodeRunnerFile.js
Упс, это видимо потому что я запускаю в vscode

2024-10-21 16:53 UTC, yzubr commented on lesson-15/src/index.js
> +    if (category !== undefined) {
Я когда это читаю, все понимаю, но когда делаю напрочь забываю(

2024-10-21 17:33 UTC, vladshcherbin approved these changes
всё хорошо, молодец 🔥

2024-10-21 17:33 UTC, vladshcherbin commented on lesson-15/src/tempCodeRunnerFile.js
лишний файлик 🥲

2024-10-21 17:59 UTC, merged

2024-10-21 18:07 UTC, vladshcherbin commented on lesson-15/src/index.js
> +    if (category !== undefined) {
@yzubr с практикой, когда пишешь такие проверки почти каждый день, запоминается быстрее - у тебя всё ещё впереди)