Add lesson-19
yzubr/courses pull request #17
Opened 2024-11-03 09:33 UTC by yzubr

2024-11-04 11:15 UTC, vladshcherbin requested changes
в целом отлично, парочка правок и рекомендаций 🙌

2024-11-04 11:15 UTC, vladshcherbin commented on lesson-19/eslint.config.js
в файлике есть ошибки eslint

2024-11-04 11:15 UTC, vladshcherbin commented on lesson-19/stylelint.config.js
в файлике есть ошибки eslint

2024-11-04 11:15 UTC, vladshcherbin commented on lesson-19/index.html
> +<html lang="en">
неверный язык

2024-11-04 11:15 UTC, vladshcherbin commented on lesson-19/index.html
> +  <link rel="stylesheet" href="style.css"> -->
```suggestion
```

2024-11-04 11:15 UTC, vladshcherbin commented on lesson-19/package.json
> +    "preview": "vite previem"
неверная команда vite

2024-11-04 11:15 UTC, vladshcherbin commented on lesson-19/package.json
> +
пустая строка

2024-11-04 11:15 UTC, vladshcherbin commented on lesson-19/src/components/footer/Footer.jsx
> +export default function Fooetr() {
осталяй отсутпы между import/export чтобы легче читалось

2024-11-04 11:15 UTC, vladshcherbin commented on lesson-19/src/components/footer/Footer.jsx
> +export default function Fooetr() {
```suggestion
export default function Footer() {
```

2024-11-04 11:15 UTC, vladshcherbin commented on lesson-19/src/components/header/Header.jsx
> +          <li className={styles['navigation-item']}><a href="#">Главная</a></li>
в футере использовал класс и в нём элементы (`.footer a`), почемы бы здесь и не использовать? тот же `.navigation li` - было бы меньше стилей)

2024-11-04 11:15 UTC, vladshcherbin commented on lesson-19/src/components/header/Header.jsx
> +        <ul className={ styles.navigation }>
```suggestion
        <ul className={styles.navigation}>
```

2024-11-04 11:15 UTC, vladshcherbin commented on lesson-19/src/components/main/App.jsx
> +export default function Section() {
```suggestion
export default function App() {
```

2024-11-04 11:15 UTC, vladshcherbin commented on lesson-19/src/components/main/App.jsx
> +          </li>
у нас 3 повторяющихся элемента курсов - попробуй вынести в отдельную переменную курсы, с массивом объектов, и вывести элементы через `.map` (как в примере урока)

таким образом если добавится новый курс или изменится разметка - поменять нужно будет всего в одном месте

2024-11-04 17:37 UTC, yzubr commented on lesson-19/src/components/header/Header.jsx
> +          <li className={styles['navigation-item']}><a href="#">Главная</a></li>
опять скажешь, что названия плохие для классов использую :)

2024-11-22 21:05 UTC, vladshcherbin approved these changes
Внёс пару правок - вынес курсы в отдельный компонент и массив, вывел используя map. Добавил максимальную ширину и центрирование

2024-11-25 21:51 UTC, merged