Add Lesson 11
yzubr/courses pull request #8
Opened 2024-10-06 20:26 UTC by yzubr

2024-10-06 20:39 UTC, vladshcherbin requested changes
Вижу, что всё для работы eslint добавил, но файлики без верного форматирования. 

Предположу, что не установлен `eslint` в `vscode` или не перезапущен `vscode` после установки.

Вот такое расширение:

<img width="1469" alt="image" src="https://github.com/user-attachments/assets/11c80825-8161-48fd-a401-070e230226aa">

Установи и проверь файлики свои. Если по какой-то другой причине, напиши

2024-10-06 21:31 UTC, vladshcherbin requested changes
Молодец, почти все задания верные, одно поправить)

для переменных, функций и т.д. используй нормальные названия и не сокращай (которые сразу будут понятны и другим разработчикам)

(поправь во всём файлике)

2024-10-06 21:31 UTC, vladshcherbin commented on Lesson 11/.eslintrc.cjs
зайди и в этот файлик, проверь на ошибки)

2024-10-06 21:31 UTC, vladshcherbin commented on Lesson 11/src/index.js
> +const s = 'agdjgfkshv'
для переменных, функций и т.д. используй нормальные названия и не сокращай (которые сразу будут понятны и другим разработчикам)

(поправь во всём файлике)

2024-10-06 21:31 UTC, vladshcherbin commented on Lesson 11/src/index.js
> +  } else console.log(`в строке ${str} нет подстроки ${substr}`)
```suggestion
  } else {
    console.log(`в строке ${str} нет подстроки ${substr}`)
  }
```

записывай условия с новой строки в фигурных
(странно, что eslint тебе не высказал 😅)

2024-10-06 21:31 UTC, vladshcherbin commented on Lesson 11/src/index.js
> +function findSubStr(str, substr) {
результат не совпадает с заданием

2024-10-07 19:41 UTC, vladshcherbin requested changes
Оставил пару улучшений

2024-10-07 19:41 UTC, vladshcherbin commented on Lesson 11/src/index.js
> +// string reverce
```suggestion
// string reverse
```

2024-10-07 19:41 UTC, vladshcherbin commented on Lesson 11/src/index.js
> +console.log(reverseStr(string10))
```suggestion
function reverseString(string) {
  return string.split('').reverse().join('')
}

console.log(reverseString(string10))
```

2024-10-07 19:41 UTC, vladshcherbin commented on Lesson 11/src/index.js
> +findSubStr('мама мыла раму', 'ла')
```suggestion
function containsSubstring(string, substring) {
  if (string.indexOf(substring) !== -1) {
    console.log(true)
  } else {
    console.log(false)
  }
}

containsSubstring('мама мыла раму', 'ла')
```

это название лучше подходит, "строка содержит" - логичнее для ответа "да" или "нет", особенно в условиях if и т.д.

2024-10-07 19:41 UTC, vladshcherbin commented on Lesson 11/src/index.js
> +function findSubStr(string, substring) {
в задании функция возвращает true или false, а не выводит

2024-10-07 19:41 UTC, vladshcherbin commented on Lesson 11/src/index.js
> +function findSubStr(string, substring) {
`indexOf` посмотрел, посмотри ещё `includes` метод вместо этого

2024-10-07 19:41 UTC, vladshcherbin commented on Lesson 11/src/index.js
> +reverceArray([1, 2, 3, 4, 5])
```suggestion
function reverseArray(initialArray) {
  console.log(initialArray.reverse())
}

reverseArray([1, 2, 3, 4, 5])
```

2024-10-07 20:26 UTC, yzubr commented on Lesson 11/src/index.js
> +function findSubStr(string, substring) {
захотелось реализовать так :) есть же множество способов. наверное менее производительно, но не факт) один unshift ниже какой непроизводительный же

2024-10-07 20:42 UTC, vladshcherbin requested changes
Скобки не нужны, в остальном 🔥

как обновишь, сразу объединяй с мастером

2024-10-07 20:42 UTC, vladshcherbin commented on Lesson 11/src/index.js
> +  return (string.includes(substring))
```suggestion
  return string.includes(substring)
```

2024-10-07 20:48 UTC, merged